/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.catedra;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lance
 */
public class BusquedaLibro extends javax.swing.JInternalFrame {

    String titulo = "";
    String autor = "";
    DefaultTableModel modelo1 = null;
    ResultSet resultado = null;
    Conexion con3 = new Conexion();
    private final java.util.Date fechaActual = new java.util.Date();
    SimpleDateFormat formateador = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat stringToDate = new SimpleDateFormat("yyyy-MM-dd");
    int proId;

    /**
     * Creates new form BusquedaLibro
     */
    public BusquedaLibro() throws SQLException {
        initComponents();
    }

    public void generarListado() throws SQLException {
        resultado = con3.getRs();
        while (resultado.next()) {
            Object[] newRow = {resultado.getString(1), resultado.getString(2), resultado.getString(3), resultado.getString(4)};
            modelo1.addRow(newRow);
        }

        // Es una buena práctica cerrar el ResultSet :v
        resultado.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnPrestar = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Búsqueda de libros");

        jLabel1.setText("Título:");

        jLabel2.setText("Autor(es):");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Título", "Autor(es)", "Copias"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        jButton1.setText("Iniciar consulta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnPrestar.setText("Prestar");
        btnPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(btnPrestar)))
                        .addContainerGap(256, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnPrestar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        titulo = jTextField1.getText();
        autor = jTextField2.getText();       

        if (jTextField1.getText().equals("") && jTextField2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor llene al menos uno de los campos de búsqueda", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Object[][] data = null;
                String[] columns = {"Código","Título", "Autor","Copias"};
                modelo1 = new DefaultTableModel(data, columns);
                this.jTable1.setModel(modelo1);
                con3.setRs("SELECT a.proIsbn,a.ProNombre, p.autNombre,COUNT(c.cpId) as copia FROM Producto a \n" +
                    "INNER JOIN ProductoAutor ap ON ap.proId = a.proId \n" +
                    "INNER JOIN Autor p ON p.autId = ap.autId\n" +
                    "INNER JOIN Copia c ON a.proId = c.proId\n" +
                    "WHERE a.proNombre LIKE '%" + titulo + "%' OR p.autNombre LIKE '%" + autor + "%' AND c.stpId = 1\n" +
                    "GROUP BY a.proIsbn,a.ProNombre,p.autNombre\n" +
                    "HAVING COUNT(c.cpId)");
                generarListado();
            } catch (SQLException e) {
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnPrestarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int fila = jTable1.rowAtPoint(evt.getPoint());
        if ((fila > -1)) {
            btnPrestar.setEnabled(true);
            String id = modelo1.getValueAt(fila, 0).toString();
            try {
                Conexion con2 = new Conexion();
                con2.setRs("SELECT proId FROM Producto WHERE proIsbn = '" + id + "'");
                resultado = (ResultSet)con2.getRs();
                resultado.next();
                proId = resultado.getInt(1);
                con2.setRs("SELECT COUNT(prstId) from Prestamo Where usrId="+ContenedorUsuario.usrId);
                con2.setQuery("INSERT INTO Prestamo(prstFechaPres,prstFechaPrevDev,prstFechaDev,usrId,proId) "
                        + "VALUES('"+formateador.format(fechaActual)+"','"+formateador.format(fechaActual) +"',null,"+Contenedor.usrId+proId+")" );
            } catch (SQLException e) {
            }
            
        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrestar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
